language: node_js
node_js:
- '12'
before_install:
- MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- echo $TRAVIS_COMMIT
- echo ${MESSAGE}
install:
- yarn
test: true
script:
- yarn docs:build
# cache: yarn
after_success:
- MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- cd dist
- cp index.html 404.html
- echo GH_TOKEN:$GH_TOKEN
- sed -i "s/GH_TOKEN:\"$GH_TOKEN\"\,/ /g" umi.js
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GH_TOKEN"
  on:
    branch: master
  repo: jsBan/blog
  target_branch: gh-pages
  local_dir: dist
env:
  global:
    secure: b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABCm0hPuL+
Y/NEGufsV8mb2BAAAAEAAAAAEAAAEXAAAAB3NzaC1yc2EAAAADAQABAAABAQCuEqU5ujYu
RJAigRietHlyjQYcnuUZ+Ls7LHX/mogoLtfDG1PHGYtywEbCCrxzjyFFMxL5jsm+MJL2NQ
aQkRX0jmYCv6Xh4Ipo9BL4h/CbperTR6w4skpej4IxwLqms/AMTUwEGtVDwhfZFppNHvUA
8x3I9+M3zmbwVL3TkfMExsG9KhB1yN9ITWJQRJCV0xJbeGBF0MfU6U5aiCoAGe1An1e60o
MhDISdssyUzO3LTgfgODEyLCSmXp39UeluRa4GePnAHfRm2UWqbSnl24Xpsud0Kf3jdD8h
KhwWpkm0zgj99s7mPsKp7BZf0E6Gx4BQkd7FqCgo+GvSJ7mWEtznAAAD0KICuSHQRXPedw
PGqxc3cA8QZziDdgE/V32p/RdhzYoMyv5lQiLf1BMj8rowF3vHbbGT7h0iQTBGMa/T6+4L
JPHZb1/NXncG43cDxoKyBjcK7NeJmK+AqsLDsT9glriFNUJ+o1ae3MBgGsydu3SWIL7BIu
H+UpXSfuv7z2aCRXOAWfqtqs/qeAMQMY/xq8EfBYxvxyFDxePVe4Ay3T81T7U/jGQEQo30
fza1UI2pn4LQIItbmZf17xYsJ9SnlAjEZS5O6s4DU6GzkAV9r+Yl5fLqSgBgOo+kfDk0iH
ZcW83aa+Zo4nEf3n40FttYZfaF4hKwaTri+vNIEBbHMB/Mv6iAdurx6YcSF5c8QaNlMhrU
iB64cBQGq44uEh8eb0LJrfFQO2ffxPC3cKNAWq1mVvjlvGjhl+n5cOEjAzMRBXKBb5u90/
fhrMR4cskvF2vBimALgmGdqfkUu++tmJMKBEksH83btDFpRJ6xMefAFha78p7v80nNT9Rt
h+1GFqm4Y/ij9GFIFPiGlgiq+sRkcFZwffvRKaotDeY2hRxhsoqaW5L/bfDYhk2gH/uWPD
tS+70jzG5chuwhw4E16hYcBHXknfkjuftI2RU+ar99ODS4eTtygJ5EU5gK1u/sYMu3Eooi
H8pfCmG4X3Sm4JFoJId8sxQRypZi7wMrbNlny7oKVI+risy3wo8Z1nX9NJTrpiEAlkYNUF
dnHYYr5w16NBcvookCWQdwKo1Rd6hOiSw0iHkQdwJpKWPyF3CDQOvJqF1CTZSaLssV1Qwa
/4VLcKOjbtBJwRn5rJGY4FiKmJ1YUdyijNBuaF8JtZktj0pfY0GLqjbI080jk+bUZNQuqU
lABSi6MdAQxCk0IKlVCAL9bs0jfkW/dyJj7m4l1IN6csNEdxXvOGQDBRGCLpGugrL5It3I
H4Zhx2fhqMLiklJxfS1rFIn3bZ4bfWaRIvOVC1U0feqLhxfjU22IYMBJ0raO2TlpZTE8vf
ldZ1yGSQ+b73Qr0XHB8bMbCxSfkPKAScrqSl1Nl1QdgZ8y2aPBCh2yckUVDj0x9RYlbd49
MMbWFTbNABQwG/9urQX4T1neSZ37MrcxAkBqLxXJexxrICNhzidlIlP1k6OQhZydLUzUmJ
ii2TmGdCACWpnIR+SZq730K2JQczJLjeKGsQYIbtmJ0tleKRcdIJp/rJ5iTLoK9VmTvXVo
Zd0GcLp+iak8Id8jmIVPgXEFCHEVuGA5AgOx/td1HFyCCABnBU4uqq0oHHAC6s75rhERhO
YyMYU5qzinwbMCWXbVQkqDH1Awqjw=
